# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(default='male', max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Sex'),
        ),
    ]
