apiVersion: v1
kind: Service
metadata:
  name: master
spec:
  type: NodePort
  ports:
    - nodePort: 30180
      port: 8000
      targetPort: 8000
  selector:
    app: master
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: master
spec:
  replicas: 1
  selector:
    app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
        - image: mycodesmells/k8s-checks-master:1
          imagePullPolicy: IfNotPresent
          name: master
          ports:
            - containerPort: 8000
          env:
            - name: ADDR
              value: :8000
            - name: WORKER_ADDR
              value: http://worker:8000
