# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bbs.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bbsuser',
            name='photo',
            field=models.ImageField(default='imgs/mm.jpg', upload_to='imgs'),
        ),
    ]
