variables:
  RELEASE_IMAGE: 663220615367.dkr.ecr.cn-northwest-1.amazonaws.com.cn/rental:$CI_COMMIT_TAG

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - $(aws ecr get-login --no-include-email --region cn-northwest-1)
    - docker build -t $RELEASE_IMAGE .
    - docker push $RELEASE_IMAGE
    - docker rmi $RELEASE_IMAGE
  only:
    - tags

deploy:
  stage: deploy
  script:
    - source ~/scripts/playbooks/pub_script/env.sh
    - ansible-playbook $PLAYBOOK_ROOT/publish/rental/rental.yml --extra-vars="hosts=dev version=$CI_COMMIT_TAG"
  only:
    - tags
